name: monex
description: Monthly expences
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  random_color: ^1.0.3
  path_provider: ^1.3.0
  sembast: ^2.4.1+1
  uuid: ^2.0.4
  percent_indicator: ^2.1.1+1
  date_picker_timeline: ^1.2.0
  jiffy: ^3.0.1
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  shared_preferences: ^0.5.6+3
  get_it: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/icons8-beetroot-and-carrot-100.png
    - assets/icons/icons8-check-for-payment-100.png
    - assets/icons/icons8-cheeseburger-100.png
    - assets/icons/icons8-cinema-100.png
    - assets/icons/icons8-money-box-100.png
    - assets/icons/icons8-online-store-100.png
    - assets/icons/icons8-receipt-approved-100.png
    - assets/icons/icons8-restaurant-100.png
    - assets/icons/icons8-tax-100.png
    - assets/icons/icons8-taxi-back-view-100.png
    - assets/icons/icons8-transaction-approved-100.png
    - assets/icons/icons8-treatment-100.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/circular-std/CircularStd-Book.otf
          weight: 400
        - asset: assets/fonts/circular-std/CircularStd-Medium.otf
          weight: 500
        - asset: assets/fonts/circular-std/CircularStd-Bold.otf
          weight: 700
        - asset: assets/fonts/circular-std/CircularStd-Black.otf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
