name: monthlyexp
description: Monthly expences
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  path_provider: ^1.3.0
  sembast: ^2.4.1+1
  uuid: ^2.0.4
  percent_indicator: ^2.1.1+1
  jiffy: ^3.0.1
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  shared_preferences: ^0.5.6+3
  package_info: ^0.4.0+17
  kumi_popup_window: ^1.0.8
  share: ^0.6.4
  superellipse_shape: ^0.1.5
  get_it: ^4.0.1
  catcher: ^0.3.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9
  pedantic: ^1.8.0

flutter:
  uses-material-design: false
  assets:
    - assets/icons/credit/
    - assets/icons/debit/

  fonts:
    - family: Worksans
      fonts:
        - asset: assets/fonts/work-sans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/work-sans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/work-sans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/work-sans/WorkSans-SemiBold.ttf
          weight: 600

    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-SemiBold.otf
          weight: 600

    - family: MIcons
      fonts:
        - asset: assets/fonts/MIcons.ttf

    - family: CIcons
      fonts:
        - asset: assets/fonts/cat_icons.otf

    - family: CatIcons
      fonts:
        - asset: assets/fonts/Monexp.ttf

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app-icon2.png"

flutter_native_splash:
  image: assets/images/app-icon2.png
  color: "474787"
  ios: false
